import { toast } from "sonner";

/**
 * Hook para exportar contenido generado a PDF o Word (.docx)
 */
export function useExportContent() {
  const exportToPDF = async (content: string, title: string, language: "es" | "en" = "es") => {
    try {
      toast.loading(language === "es" ? "Generando PDF..." : "Generating PDF...", { id: "export-pdf" });

      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;

      // Header
      doc.setFillColor(37, 99, 235); // blue-600
      doc.rect(0, 0, pageWidth, 18, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("ContentAI", margin, 12);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.text(new Date().toLocaleDateString(language === "es" ? "es-MX" : "en-US"), pageWidth - margin, 12, { align: "right" });

      // Title
      doc.setTextColor(17, 24, 39); // gray-900
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      const titleLines = doc.splitTextToSize(title, contentWidth);
      doc.text(titleLines, margin, 32);

      // Divider
      const titleHeight = titleLines.length * 7;
      doc.setDrawColor(229, 231, 235); // gray-200
      doc.setLineWidth(0.5);
      doc.line(margin, 32 + titleHeight + 2, pageWidth - margin, 32 + titleHeight + 2);

      // Content
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(55, 65, 81); // gray-700

      // Clean markdown
      const cleanContent = content
        .replace(/\*\*(.*?)\*\*/g, "$1")
        .replace(/\*(.*?)\*/g, "$1")
        .replace(/#{1,6}\s/g, "")
        .replace(/`{1,3}(.*?)`{1,3}/g, "$1")
        .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1");

      const lines = doc.splitTextToSize(cleanContent, contentWidth);
      let y = 32 + titleHeight + 10;

      for (const line of lines) {
        if (y > pageHeight - 20) {
          doc.addPage();
          // Mini header on new pages
          doc.setFillColor(37, 99, 235);
          doc.rect(0, 0, pageWidth, 10, "F");
          doc.setTextColor(255, 255, 255);
          doc.setFontSize(8);
          doc.text("ContentAI", margin, 7);
          doc.setTextColor(55, 65, 81);
          doc.setFontSize(10);
          y = 18;
        }
        doc.text(line, margin, y);
        y += 5.5;
      }

      // Footer
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(156, 163, 175); // gray-400
        doc.text(
          language === "es" ? `Generado por ContentAI · Página ${i} de ${pageCount}` : `Generated by ContentAI · Page ${i} of ${pageCount}`,
          pageWidth / 2,
          pageHeight - 8,
          { align: "center" }
        );
      }

      const safeTitle = title.replace(/[^a-z0-9]/gi, "_").toLowerCase().slice(0, 40);
      doc.save(`contentai_${safeTitle}.pdf`);
      toast.success(language === "es" ? "PDF descargado" : "PDF downloaded", { id: "export-pdf" });
    } catch (err) {
      console.error("PDF export error:", err);
      toast.error(language === "es" ? "Error al generar el PDF" : "Error generating PDF", { id: "export-pdf" });
    }
  };

  const exportToWord = async (content: string, title: string, language: "es" | "en" = "es") => {
    try {
      toast.loading(language === "es" ? "Generando Word..." : "Generating Word...", { id: "export-word" });

      const { Document, Packer, Paragraph, TextRun, HeadingLevel, BorderStyle } = await import("docx");

      // Parse content into paragraphs
      const lines = content.split("\n");
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const docChildren: any[] = [];

      // Title paragraph
      docChildren.push(
        new Paragraph({
          text: title,
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 200 },
        })
      );

      // Metadata
      docChildren.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `${language === "es" ? "Generado por ContentAI" : "Generated by ContentAI"} · ${new Date().toLocaleDateString(language === "es" ? "es-MX" : "en-US")}`,
              color: "6B7280",
              size: 18,
              italics: true,
            }),
          ],
          spacing: { after: 400 },
          border: {
            bottom: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
          },
        })
      );

      // Content paragraphs
      for (const line of lines) {
        if (!line.trim()) {
          docChildren.push(new Paragraph({ text: "", spacing: { after: 100 } }));
          continue;
        }

        // Detect headings
        const h1Match = line.match(/^# (.+)/);
        const h2Match = line.match(/^## (.+)/);
        const h3Match = line.match(/^### (.+)/);
        const bulletMatch = line.match(/^[-*•] (.+)/);

        if (h1Match) {
          docChildren.push(new Paragraph({ text: h1Match[1], heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 100 } }));
        } else if (h2Match) {
          docChildren.push(new Paragraph({ text: h2Match[1], heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 100 } }));
        } else if (h3Match) {
          docChildren.push(new Paragraph({ text: h3Match[1], heading: HeadingLevel.HEADING_4, spacing: { before: 150, after: 80 } }));
        } else if (bulletMatch) {
          docChildren.push(new Paragraph({
            children: [new TextRun({ text: bulletMatch[1], size: 22 })],
            bullet: { level: 0 },
            spacing: { after: 80 },
          }));
        } else {
          // Clean markdown bold/italic
          const cleanLine = line
            .replace(/\*\*(.*?)\*\*/g, "$1")
            .replace(/\*(.*?)\*/g, "$1")
            .replace(/`(.*?)`/g, "$1");

          docChildren.push(new Paragraph({
            children: [new TextRun({ text: cleanLine, size: 22 })],
            spacing: { after: 120 },
          }));
        }
      }

      const doc = new Document({
        creator: "ContentAI",
        title,
        description: language === "es" ? "Contenido generado por ContentAI" : "Content generated by ContentAI",
        sections: [{
          properties: {},
          children: docChildren,
        }],
      });

      const buffer = await Packer.toBlob(doc);
      const url = URL.createObjectURL(buffer);
      const a = document.createElement("a");
      const safeTitle = title.replace(/[^a-z0-9]/gi, "_").toLowerCase().slice(0, 40);
      a.href = url;
      a.download = `contentai_${safeTitle}.docx`;
      a.click();
      URL.revokeObjectURL(url);

      toast.success(language === "es" ? "Word descargado" : "Word downloaded", { id: "export-word" });
    } catch (err) {
      console.error("Word export error:", err);
      toast.error(language === "es" ? "Error al generar el Word" : "Error generating Word", { id: "export-word" });
    }
  };

  return { exportToPDF, exportToWord };
}
